# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed29028056cec78f71556c727a85297f9dd20fa4ab3acbc43d7b76fa53c1389777ed927edb3766990d17d9f9da17b84329e8bc264f77e4a11cec02fefb253c8c

test:
  secret_key_base: ba85618670b1349141f064417509cb5ad772be3861f7054f95ed0747396db35266347e6b2ef6a86083150ea0763bcc61839cbfc3260b25b344bf167c9cd69a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
